# Generated by Django 6.0.4 on 2026-04-28 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('hospital', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('condition_type', models.CharField(choices=[('chronic', 'Chronic Illness'), ('post_surgical', 'Post-Surgical'), ('acute', 'Acute Illness'), ('other', 'Other')], max_length=20)),
                ('diagnosis', models.TextField()),
                ('discharge_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_patients', to=settings.AUTH_USER_MODEL)),
                ('assigned_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.BooleanField(default=False)),
                ('pain', models.BooleanField(default=False)),
                ('difficulty_breathing', models.BooleanField(default=False)),
                ('wound_issues', models.BooleanField(default=False)),
                ('nausea_vomiting', models.BooleanField(default=False)),
                ('dizziness', models.BooleanField(default=False)),
                ('feeling_well', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('green', 'Stable'), ('yellow', 'Needs Attention'), ('red', 'Critical')], max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('simulated', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('direction', models.CharField(choices=[('out', 'Outbound'), ('in', 'Inbound')], max_length=10)),
                ('status', models.CharField(default='delivered', max_length=20)),
                ('simulated', models.BooleanField(default=True)),
                ('twilio_sid', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='core.patient')),
            ],
        ),
    ]
