# Generated by Django 5.1.4 on 2026-05-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doctoralert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='checkin_token',
            field=models.CharField(blank=True, max_length=48, unique=True),
        ),
    ]
